sudo: false
language: python

before_install:
    - pip install ipython

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - 3.7

install:
    - pip install .

script:
    py.test -k 'not integration'
